"""unique organization name

Revision ID: 9ae7cc106744
Revises: 842ae59fe36e
Create Date: 2022-10-23 19:29:05.439702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ae7cc106744"
down_revision = "842ae59fe36e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix__name", table_name="organization", schema="shop")
    op.create_unique_constraint(
        op.f("uq__organization__name"), "organization", ["name"], schema="shop"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq__organization__name"),
        "organization",
        schema="shop",
        type_="unique",
    )
    op.create_index(
        "ix__name", "organization", ["name"], unique=False, schema="shop"
    )
    # ### end Alembic commands ###
