"""unique equipment_balance serial_number

Revision ID: 9e3348faf429
Revises: 91e208eb921f
Create Date: 2022-10-24 01:09:59.335388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e3348faf429"
down_revision = "91e208eb921f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq__equipment_balance__serial_number"),
        "equipment_balance",
        ["serial_number"],
        schema="shop",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq__equipment_balance__serial_number"),
        "equipment_balance",
        schema="shop",
        type_="unique",
    )
    # ### end Alembic commands ###
