"""unique equipment_postion name

Revision ID: 91e208eb921f
Revises: 9ae7cc106744
Create Date: 2022-10-23 21:32:15.536843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "91e208eb921f"
down_revision = "9ae7cc106744"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq__equipment_positions__name"),
        "equipment_positions",
        ["name"],
        schema="shop",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq__equipment_positions__name"),
        "equipment_positions",
        schema="shop",
        type_="unique",
    )
    # ### end Alembic commands ###
