version: '3.9'

services:
  postgresql:
    image: postgres:14.3
    container_name: postgresql-edu
    environment:
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./shared/:/shared:rw
    ports:
      - 5432:5432
