version: '3.9'

services:
  postgresql:
    image: postgres:14.3
    container_name: postgresql-edu
    environment:
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./shared/:/shared:rw
    ports:
      - 5432:5432
  
  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin-edu
    environment:
      - PGADMIN_DEFAULT_EMAIL=wallseat@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - 8000:80 
  mongo:
    image: mongo
    container_name: mongo-edu
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

    ports:
      - 27017:27017
